#Application Configuration
server:
  port: 8006

spring:
  application:
    name: tag-service
  #Kafka Config
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ev-consumer
      auto-offset-reset: latest
  #Monodb Config
  data:
    mongodb:
      database: empty_db
      host: localhost
      port: 27017

#Service Discovery Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging
logging:
  level:
    org.springframework.data.mongodb: DEBUG
