#Application Configuration
server:
  port: 8002

#Monodb Configuration
spring:
  application:
    name: comment-service
  data:
    mongodb:
      database: empty_db
      host: localhost
      port: 27017
  datasource:
    schema:
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging
logging:
  level:
    org.springframework.data.mongodb: DEBUG

