version: "2"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    container_name: admin-mongo
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    networks:
      - mongo-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - kafka-network
    ports:
      - 9092:9092
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ev-eureka-server:
    build: ./ev-eureka-server
    container_name: ev-eureka-server
    ports:
      - "8761:8761"
    networks:
      - gateway-network

  ev-api-gateway:
    build: ./ev-api-gateway
    container_name: ev-api-gateway
    ports:
      - "8000:8000"
    networks:
      - gateway-network

  ev-user-service:
    build: ./ev-user-service
    container_name: ev-user-service
    networks:
      - mongo-network
      - kafka-network
      - gateway-network

  ev-comment-service:
    build: ./ev-comment-service
    container_name: ev-comment-service
    networks:
      - mongo-network
      - kafka-network
      - gateway-network

  ev-dan-service:
    build: ./ev-dan-service
    container_name: ev-dan-service
    networks:
      - mongo-network
      - kafka-network
      - gateway-network

  ev-fav-list-service:
    build: ./ev-fav-list-service
    container_name: ev-fav-list-service
    networks:
      - mongo-network
      - kafka-network
      - gateway-network

  ev-history-service:
    build: ./ev-history-service
    container_name: ev-history-service
    networks:
      - mongo-network
      - kafka-network
      - gateway-network

  ev-notification-service:
    build: ./ev-notification-service
    container_name: ev-notification-service
    networks:
      - mongo-network
      - kafka-network
      - gateway-network

  ev-tag-service:
    build: ./ev-tag-service
    container_name: ev-tag-service
    networks:
      - mongo-network
      - kafka-network
      - gateway-network

  ev-video-service:
    build: ./ev-video-service
    container_name: ev-video-service
    networks:
      - mongo-network
      - kafka-network
      - gateway-network

  ev-oauth2-service:
    build: ./ev-oauth2-service
    container_name: ev-oauth2-service
    ports:
      - "8011:8011"
    networks:
      - mongo-network
      - kafka-network
      - gateway-network

networks:
  gateway-network:
  mongo-network:
  kafka-network: