server:
  port: 8000
  use-forward-headers: true

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  sensitive-headers:
    - Cookie
    - Set-Cookie

logging:
  level:
    org.springframework.cloud.netflix: true