#Application Configuration
server:
  port: 0

#Monodb Configuration
spring:
  application:
    name: dan-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ev-consumer
      auto-offset-reset: latest
  data:
    mongodb:
      database: empty_db
      host: localhost
      port: 27017

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging
logging:
  level:
    org.springframework.data.mongodb: DEBUG
