#Application Configuration
server:
  port: 8011

spring:
  application:
    name: oauth2-service
  thymeleaf:
    reactive:
      max-chunk-size: 8192

  #Monodb Configuration
  data:
    mongodb:
      database: empty_db
      host: localhost
      port: 27017

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging
logging:
  level:
    org.springframework.data.mongodb: DEBUG
