package com.empty.domain;

public enum OperationEnum {
    LOGIN,
    ACTIVATE_A_USER,
    UPDATE_A_USER,

    WRITE_A_COMMENT,
    LIKE_A_COMMENT,
    CANCEL_LIKE_A_COMMENT,
    DELETE_A_COMMENT,

    POST_A_VIDEO,
    LIKE_A_VIDEO,
    CANCEL_LIKE_A_VIDEO,
    UNLIKE_A_VIDEO,
    CANCEL_UNLIKE_A_VIDEO,
    FAV_A_VIDEO,
    TAG_A_VIDEO,
    VIEW_A_VIDEO,

    SEND_A_MESSAGE,

    GET_POINTS,
}
